#Mon Jan 06 10:57:12 HKT 2025
APP_PLATFORM=Android
APP_PROFILE=PRODUCTION
APP_VERSION=2025.01.06
APP_VERSION_CODE=6262
APP_VERSION_CODENAME=SG3
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding\=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M"
xcodeproj=~/iosApp
